# Site
name: Techskilld
description: A tech & business blogging | creative for all
meta_description: "A tech & business blogging"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
paginate: 12
baseurl: 
email: 'info@techskilld.com'
google_analytics: 'UA-117349329-1'
disqus: 'techskilld'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Techskilld
    display_name: Techskilld
    gravatar: 
    email: info@techskilld.com
    web: https://www.techskilld.com/
    twitter: https://twitter.com/techskilld
    description: "An innovative and agile tech company that focus on analyzing the current trends of the target market and create very simple and customized IT & business strategy solutions, using the latest technologies and compelling experience to offer best products & services in software & website development, creative design & printing, online marketing, social media management, customized pieces of training and consultation which will give clients the total possible satisfaction.
"
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge